[workspace]
resolver = "2"
members = [
    "crates/message-phone",
    "crates/message-csv",
    "crates/message-ir",
    "crates/message-mail",
    "crates/message-sbr",
    "crates/message-contacts",
    "crates/message-obfuscate",
    "crates/message-media",
    "crates/go-sms-pro-exporter",
    "crates/sms-backup-restore-exporter",
    "crates/sms-backup-plus-exporter",
    "crates/openextract-exporter",
    "crates/imazing-exporter",
    "crates/imessage-ir-exporter",
    "crates/whatsapp-exporter",
    "crates/message-reexporter",
    "crates/message-exporters-core",
    "crates/message-exporters-gui",
]
