[workspace]
resolver = "2"
members = [
    "crates/message-phone",
    "crates/message-csv",
    "crates/message-contacts",
    "crates/message-obfuscate",
    "crates/message-media",
    "crates/go-sms-pro-export",
    "crates/sms-backup-restore-export",
    "crates/sms-backup-plus-export",
    "crates/openextract-export",
    "crates/imazing-export",
    "crates/imessage-exporter",
    "crates/message-exporters-core",
    "crates/message-exporters-gui",
]
